version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: skillglide_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: jobify
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - skillglide_network

  # Redis for caching and background tasks
  redis:
    image: redis:7-alpine
    container_name: skillglide_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - skillglide_network

  # FastAPI Backend
  backend:
    build: .
    container_name: skillglide_backend
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/jobify?authSource=admin
      - MONGODB_DB_NAME=jobify
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    networks:
      - skillglide_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery Worker for background tasks
  celery_worker:
    build: .
    container_name: skillglide_celery_worker
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/jobify?authSource=admin
      - MONGODB_DB_NAME=jobify
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./app:/app/app
    networks:
      - skillglide_network
    command: celery -A app.tasks.celery worker --loglevel=info

  # Celery Beat for scheduled tasks
  celery_beat:
    build: .
    container_name: skillglide_celery_beat
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/jobify?authSource=admin
      - MONGODB_DB_NAME=jobify
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./app:/app/app
    networks:
      - skillglide_network
    command: celery -A app.tasks.celery beat --loglevel=info

volumes:
  mongodb_data:
  redis_data:

networks:
  skillglide_network:
    driver: bridge